### ISSUE TITLE
Update: crystal-open 2.178.2

### ISSUE THREAD

**Issue by Querela** [ELTE-DH/NoSketch-Engine-Docker#23]
Hi, the NSE sources have an update:
- https://nlp.fi.muni.cz/trac/noske
- [​`crystal-open-2.178.2.tar.gz`](https://corpora.fi.muni.cz/noske/current/src/crystal-open-2.178.2.tar.gz) (old: `crystal-open-2.166.4.tar.gz`)

We based our changes on your setup but did not find major conflicts. Our files with the updated sources files integrated: https://github.com/Leipzig-Corpora-Collection/NoSketch-Engine-Docker/commit/200c440cf806159ec44ceaa809d6d5501ba69351.
But the `crystal-open-2.178.2/app/src/dashboard/page-dashboard.tag` has been changed, in particular the section with the `CITATION_LINK_PLACEHOLDER`. So you need to check when updating your files or merging the changes.

**Comment by dlazesz** [comment]
Thank you!
I must have missed the announcement.
I have updated the repo in 2fe965f4a01901b8f28c452b867f85726fa8d80e.

**Comment by Querela** [comment]
Now I have to ask. There are announcements? I have to regularly look and compare versions to see if there are updates ...

**Comment by dlazesz** [comment]
That is a good strategy, but I tend to forget to check regularly. :smile: 

About announcements:

The last "real" one:

[New version of NoSketch Engine (manatee ​​2.225.8 / bonito 5.71.15 / gdex 4.13.2 / crystal 2.166.4)
](https://groups.google.com/a/sketchengine.co.uk/g/noske/c/K1lcmGjQ1qY)

The really last, but sneaky one:

> Dear Kristina,
> the problem with links from annotation to concordance was fixed in the latest NoSketch Engine (Crystal-open 2.178.2). Of course, for the changes to take effect, Crystal must be installed on [clarin.si](http://clarin.si/).
> 
> Best regards!
> 
> Tomas

Source: https://groups.google.com/a/sketchengine.co.uk/g/noske/c/NuMgmUpyOJI/m/y5TWySNbAQAJ

I was waiting for it to be made official, which has not happened to date. And I completely forgot about it.

I'm curious if there will be a hotfix if [this bug](https://groups.google.com/a/sketchengine.co.uk/g/noske/c/wqG9MCe0muM/m/CXFCF1yyBgAJ) turns out to be real. :eyes:

**Comment by Querela** [comment]
Ah. Thank you. I should have thought about the Google Groups for update news.
